module.exports = {
  license: [
    {
      type: 'doc',
      id: 'license',
    },
    {
      type: 'category',
      label: 'Dreamcatcher License',
      items: [{ type: 'autogenerated', dirName: 'DPL' }],
    },
  ],

}
