module.exports = {
  apps: [
    {
      type: 'doc',
      id: 'apps-overview',
    },
    {
      type: 'doc',
      id: 'wp_appstore',
    },
    {
      type: 'category',
      label: 'Apps',
      items: [{ type: 'autogenerated', dirName: 'Apps' }],
    },
  ],
}
