module.exports = {
  license: [
    {
      type: 'category',
      label: 'Whitepapers',
      items: [
        'wp_dreamcatcher',
      ],
    },
    {
      type: 'category',
      label: 'Dreamcatcher License',
      items: [{ type: 'autogenerated', dirName: 'DPL' }],
    },
  ],

}
