module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'Dreamcatcher Charter',
    },
    
    {
      type: 'doc',
      id: 'Tweets',
    },
    {
      type: 'category',
      label: 'Whitepapers',
      items: [
        'wp_dreamcatcher',
        'wp_inversion',
        'wp_appstore',
      ],
    },

    {
      type: 'category',
      label: 'Dreamcatcher License',
      items: [{ type: 'autogenerated', dirName: 'DPL' }],
    },
    {
      type: 'category',
      label: 'References',
      items: [
        {
          type: 'autogenerated',
          dirName: 'References',
        },
      ],
    },
    {
      type: 'category',
      label: 'DRAFTS',
      items: [
        {
          type: 'autogenerated',
          dirName: 'DRAFTS',
        },
      ],
    },
  ],
}
