module.exports = {
  nfas: [
    {
      type: 'category',
      label: 'Requests',
      items: [{ type: 'autogenerated', dirName: 'Requests' }],
    },
    {
      type: 'category',
      label: 'Ideas',
      items: [{ type: 'autogenerated', dirName: 'Ideas' }],
    },
    {
      type: 'category',
      label: 'Drafts',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'Drafts' }],
    },
  ],
}
