module.exports = {
  license: [
    { type: 'doc', id: 'dictionary-overview' },
  {
      type: 'doc',
      id: 'Dictionary_Conventions',
    },
{
      type: 'category',
      label: 'User Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'User_Dictionary',
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Architecture_Dictionary',
        },
      ],
    },
    {
      type: 'category',
      label: 'DOS Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'DOS_Dictionary',
        },
      ],
    },
  ],

}
