module.exports = {
  nfas: [
    {
      type: 'doc',
      id: 'Roadmap',
    },
    {
      type: 'category',
      label: 'NFAs',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'NFAs' }],
    },
  ],
}
