module.exports = {
  interblock: [
  { type: 'doc', id: 'interblock-overview' },
    { type: 'doc', id: 'spec/Specification' },
    {
      type: 'category',
      label: 'Whitepapers',
      items: [
        'wp_dos',
        'wp_interblock',
      ],
    },
    {
      type: 'category',
      label: 'Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'dictionary',
        },
      ],
    },
  ],
}
