module.exports = {
  license: [
    {
      type: 'category',
      label: 'Whitepapers',
      items: [
        'wp_dreamcatcher',
      ],
    },
{
      type: 'category',
      label: 'User Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'User_Dictionary',
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Architecture_Dictionary',
        },
      ],
    },
    {
      type: 'category',
      label: 'DOS Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'DOS_Dictionary',
        },
      ],
    },
  ],

}
