module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'Dreamcatcher Charter',
    },
    {
      type: 'doc',
      id: 'Tweets',
    },
    {
      type: 'category',
      label: 'Apps',
      items: [{ type: 'autogenerated', dirName: 'Apps' }],
    },
    {
      type: 'category',
      label: 'Whitepapers',
      items: [
        'wp_dreamcatcher',
        'wp_dos',
        'wp_interblock',
        'wp_inversion',
        'wp_appstore',
      ],
    },
    // Features: ['mdx'],
    { type: 'doc', id: 'spec/Specification' },
    {
      type: 'category',
      label: 'Dreamcatcher License',
      items: [{ type: 'autogenerated', dirName: 'DPL' }],
    },
    {
      type: 'doc',
      id: 'Dictionary_Conventions',
    },
    {
      type: 'category',
      label: 'User Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'User_Dictionary',
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Architecture_Dictionary',
        },
      ],
    },
    {
      type: 'category',
      label: 'DOS Dictionary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'DOS_Dictionary',
        },
      ],
    },
    {
      type: 'category',
      label: 'References',
      items: [
        {
          type: 'autogenerated',
          dirName: 'References',
        },
      ],
    },
    {
      type: 'category',
      label: 'DRAFTS',
      items: [
        {
          type: 'autogenerated',
          dirName: 'DRAFTS',
        },
      ],
    },
  ],
  // api: [{ type: 'category', label: 'API', collapsed: false, items: [] }],
}
